### PR TITLE
Maxk

### PR DESCRIPTION
**Pull request by mkayen**
This removes all errors that come up in logs from the homepage, neatens up text margins while allowing header image to span

### CODE REVIEW

**Comment by dtrodrigues** [comment]
The page is requesting but not finding "/assets/bootstrap.css.map". Can you take care of that before I merge your changes? Also, maybe have the "Read More..." links just be links back to the home page so they're not broken links to blog-post.html.  I have a couple other minor suggestions for the layout, but I'll put them in their own issues.

**Comment by mkayen** [comment]
Hmm - Is this coming up on the Heroku logs? I'm not seeing this on the
local machine

On Sun, Aug 31, 2014 at 8:40 PM, Dustin Rodrigues notifications@github.com
wrote:

> The page is requesting but not finding "/assets/bootstrap.css.map". Can
> you take care of that before I merge your changes? Also, maybe have the
> "Read More..." links just be links back to the home page so they're not
> broken links to blog-post.html. I have a couple other minor suggestions for
> the layout, but I'll put them in their own issues.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mkayen/CouchMVP/pull/7#issuecomment-54006613.

## 

Max Kayen
(516 375 5270)
mkayen@gmail.com

**Comment by dtrodrigues** [comment]
Weird, I'm not seeing the error anymore, so don't worry about that. One other minor issue though - the green "Sign up" over the main image points to sign-up.html and not to the actual sign up page.

**Comment by mkayen** [comment]
Fixed, and pushed to my branch. Thanks for pointing that out.

On Sun, Aug 31, 2014 at 8:59 PM, Dustin Rodrigues notifications@github.com
wrote:

> Weird, I'm not seeing the error anymore, so don't worry about that. One
> other minor issue though - the green "Sign up" over the main image points
> to sign-up.html and not to the actual sign up page.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mkayen/CouchMVP/pull/7#issuecomment-54007054.

## 

Max Kayen
(516 375 5270)
mkayen@gmail.com

**Comment by mkayen** [comment]
I'll put in a new pull request

On Sun, Aug 31, 2014 at 9:06 PM, Max Kayen mkayen@gmail.com wrote:

> Fixed, and pushed to my branch. Thanks for pointing that out.
> 
> On Sun, Aug 31, 2014 at 8:59 PM, Dustin Rodrigues <
> notifications@github.com> wrote:
> 
> > Weird, I'm not seeing the error anymore, so don't worry about that. One
> > other minor issue though - the green "Sign up" over the main image points
> > to sign-up.html and not to the actual sign up page.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/mkayen/CouchMVP/pull/7#issuecomment-54007054.
> 
> ## 
> 
> Max Kayen
> (516 375 5270)
> mkayen@gmail.com

## 

Max Kayen
(516 375 5270)
mkayen@gmail.com

**Pull request merged**
